const videojuegos = [
  {
    id: "1",
    nombre: "The Witcher 3: Wild Hunt",
    genero: "RPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Aventura épica de mundo abierto con Geralt de Rivia cazando monstruos en un universo de fantasía oscura",
    precio: "39.99",
    tematica: "Fantasía Medieval",
    desarrollador: "CD Projekt Red",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
  },
  {
    id: "2",
    nombre: "Elden Ring",
    genero: "Souls-like",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "RPG de acción desafiante creado por FromSoftware y George R.R. Martin en mundo abierto sombrío",
    precio: "59.99",
    tematica: "Fantasía Oscura",
    desarrollador: "FromSoftware",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
  },
  {
    id: "3",
    nombre: "Red Dead Redemption 2",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Épica del viejo oeste con narrativa cinematográfica y mundo abierto detallado",
    precio: "59.99",
    tematica: "Western",
    desarrollador: "Rockstar Games",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
  },
  {
    id: "4",
    nombre: "God of War (2018)",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Reinvención de la saga con Kratos y Atreus explorando la mitología nórdica",
    precio: "49.99",
    tematica: "Mitología Nórdica",
    desarrollador: "Santa Monica Studio",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
  },
  {
    id: "5",
    nombre: "The Last of Us Part II",
    genero: "Acción/Aventura",
    plataforma: "PS5",
    descripcion:
      "Secuela post-apocalíptica con narrativa madura sobre venganza y redención",
    precio: "59.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Naughty Dog",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1594110/header.jpg",
  },
  {
    id: "6",
    nombre: "Baldur's Gate 3",
    genero: "RPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "RPG táctico basado en Dungeons & Dragons con libertad narrativa extrema",
    precio: "59.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Larian Studios",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
  },
  {
    id: "7",
    nombre: "Cyberpunk 2077",
    genero: "RPG/Acción",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "RPG de mundo abierto en Night City con implantes cibernéticos y decisiones morales",
    precio: "59.99",
    tematica: "Cyberpunk",
    desarrollador: "CD Projekt Red",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
  },
  {
    id: "8",
    nombre: "Horizon Zero Dawn",
    genero: "Acción/RPG",
    plataforma: "PC/PS5",
    descripcion:
      "Mundo post-apocalíptico dominado por máquinas prehistóricas cazadas por Aloy",
    precio: "49.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Guerrilla Games",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg",
  },
  {
    id: "9",
    nombre: "Ghost of Tsushima",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Samurái Jin Sakai defiende la isla de Tsushima de invasión mongola en 1274",
    precio: "59.99",
    tematica: "Japón Feudal",
    desarrollador: "Sucker Punch",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1817190/header.jpg",
  },
  {
    id: "10",
    nombre: "Hades",
    genero: "Roguelike",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Roguelike narrativo donde Zagreo escapa del inframundo griego con combate dinámico",
    precio: "24.99",
    tematica: "Mitología Griega",
    desarrollador: "Supergiant Games",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg",
  },
  {
    id: "11",
    nombre: "Sekiro: Shadows Die Twice",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Shinobi en Japón del período Sengoku con combate basado en paradas y postura",
    precio: "59.99",
    tematica: "Japón Feudal",
    desarrollador: "FromSoftware",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg",
  },
  {
    id: "12",
    nombre: "Persona 5 Royal",
    genero: "JRPG",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "JRPG estilizado sobre ladrones de corazones que cambian la sociedad corrupta",
    precio: "59.99",
    tematica: "Contemporáneo/Fantasía",
    desarrollador: "Atlus",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg",
  },
  {
    id: "13",
    nombre: "Divinity: Original Sin 2",
    genero: "RPG",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "RPG táctico cooperativo con combate por turnos basado en elementos y física",
    precio: "44.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Larian Studios",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/header.jpg",
  },
  {
    id: "14",
    nombre: "Dark Souls 3",
    genero: "Souls-like",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Conclusión de la trilogía Souls con combate preciso en reino decadente",
    precio: "39.99",
    tematica: "Fantasía Oscura",
    desarrollador: "FromSoftware",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg",
  },
  {
    id: "15",
    nombre: "Bloodborne",
    genero: "Souls-like",
    plataforma: "PS4/PS5",
    descripcion:
      "Acción gótica victoriana con horror lovecraftiano y transformaciones bestiales",
    precio: "19.99",
    tematica: "Horror Gótico",
    desarrollador: "FromSoftware",
    año: "2015",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/8/8/772488_front.jpg",
  },
  {
    id: "16",
    nombre: "Spider-Man (2018)",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Peter Parker balancea vida personal y protección de Nueva York con mecánicas fluidas",
    precio: "49.99",
    tematica: "Superhéroes",
    desarrollador: "Insomniac Games",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
  },
  {
    id: "17",
    nombre: "Zelda: Breath of the Wild",
    genero: "Acción/Aventura",
    plataforma: "Switch",
    descripcion:
      "Reinvención de Zelda con mundo abierto físico y libertad total de exploración",
    precio: "59.99",
    tematica: "Fantasía",
    desarrollador: "Nintendo",
    año: "2017",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/5/6/688736_front.jpg",
  },
  {
    id: "18",
    nombre: "Zelda: Tears of the Kingdom",
    genero: "Acción/Aventura",
    plataforma: "Switch",
    descripcion:
      "Secuela de BotW con mecánicas de construcción y exploración vertical expandida",
    precio: "69.99",
    tematica: "Fantasía",
    desarrollador: "Nintendo",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/5/5/3725825_front.jpg",
  },
  {
    id: "19",
    nombre: "Super Mario Odyssey",
    genero: "Plataformas",
    plataforma: "Switch",
    descripcion:
      "Aventura 3D de Mario capturando enemigos con Cappy en mundos diversos",
    precio: "59.99",
    tematica: "Fantasía",
    desarrollador: "Nintendo",
    año: "2017",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/5/2/744482_front.jpg",
  },
  {
    id: "20",
    nombre: "Hollow Knight",
    genero: "Metroidvania",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Metroidvania oscuro explorando Hallownest con combate preciso y atmosfera melancólica",
    precio: "14.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Team Cherry",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
  },
  {
    id: "21",
    nombre: "Celeste",
    genero: "Plataformas",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Plataformas precisas sobre salud mental escalando montaña mágica",
    precio: "19.99",
    tematica: "Contemporáneo",
    desarrollador: "Maddy Makes Games",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg",
  },
  {
    id: "22",
    nombre: "Dead Cells",
    genero: "Roguelike/Metroidvania",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Roguelite de acción 2D con combate rápido y progresión permanente",
    precio: "24.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Motion Twin",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/588650/header.jpg",
  },
  {
    id: "23",
    nombre: "Stardew Valley",
    genero: "Simulación",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Simulador de granja relajante con agricultura minería pesca y vida social",
    precio: "14.99",
    tematica: "Contemporáneo",
    desarrollador: "ConcernedApe",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg",
  },
  {
    id: "24",
    nombre: "Disco Elysium",
    genero: "RPG",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "RPG narrativo sin combate sobre detective amnésico en ciudad decadente",
    precio: "39.99",
    tematica: "Contemporáneo",
    desarrollador: "ZA/UM",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg",
  },
  {
    id: "25",
    nombre: "Outer Wilds",
    genero: "Aventura/Puzzle",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Exploración espacial en bucle temporal de 22 minutos descubriendo civilización alienígena",
    precio: "24.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Mobius Digital",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/753640/header.jpg",
  },
  {
    id: "26",
    nombre: "Return of the Obra Dinn",
    genero: "Puzzle/Aventura",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Misterio detectivesco deduciendo 60 muertes en barco fantasma del siglo XIX",
    precio: "19.99",
    tematica: "Histórico",
    desarrollador: "Lucas Pope",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/602760/header.jpg",
  },
  {
    id: "27",
    nombre: "Control",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Directora del Bureau investiga fenómenos paranormales en edificio cambiante",
    precio: "29.99",
    tematica: "Sobrenatural",
    desarrollador: "Remedy Entertainment",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg",
  },
  {
    id: "28",
    nombre: "Death Stranding",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Sam Porter reconecta América post-apocalíptica entregando paquetes en terreno hostil",
    precio: "39.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Kojima Productions",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1190460/header.jpg",
  },
  {
    id: "29",
    nombre: "Metro Exodus",
    genero: "FPS/Survival",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Shooter post-nuclear atravesando Rusia en tren Aurora con recursos limitados",
    precio: "39.99",
    tematica: "Post-apocalíptico",
    desarrollador: "4A Games",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/412020/header.jpg",
  },
  {
    id: "30",
    nombre: "Resident Evil 2 Remake",
    genero: "Survival Horror",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Remake del clásico survival horror en Raccoon City durante brote zombie",
    precio: "39.99",
    tematica: "Horror/Zombies",
    desarrollador: "Capcom",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/883710/header.jpg",
  },
  {
    id: "31",
    nombre: "Resident Evil Village",
    genero: "Survival Horror",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Ethan Winters busca a su hija en pueblo europeo con criaturas licántropas",
    precio: "59.99",
    tematica: "Horror Gótico",
    desarrollador: "Capcom",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1196590/header.jpg",
  },
  {
    id: "32",
    nombre: "Doom Eternal",
    genero: "FPS",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Shooter frenético cazando demonios en Tierra y otros planetas con arsenal brutal",
    precio: "39.99",
    tematica: "Ciencia Ficción/Horror",
    desarrollador: "id Software",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg",
  },
  {
    id: "33",
    nombre: "Titanfall 2",
    genero: "FPS",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Shooter con parkour fluido y mechas gigantes Titanes en campaña memorable",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Respawn Entertainment",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1237970/header.jpg",
  },
  {
    id: "34",
    nombre: "Prey (2017)",
    genero: "FPS/Immersive Sim",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Inmersive sim en estación espacial Talos I infestada por alienígenas Typhon",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Arkane Studios",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/475150/header.jpg",
  },
  {
    id: "35",
    nombre: "Dishonored 2",
    genero: "Acción/Stealth",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Sigilo supernatural como Corvo o Emily recuperando trono en Karnaca steampunk",
    precio: "39.99",
    tematica: "Steampunk",
    desarrollador: "Arkane Studios",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/323800/header.jpg",
  },
  {
    id: "36",
    nombre: "Deathloop",
    genero: "FPS/Acción",
    plataforma: "PC/PS5",
    descripcion:
      "Asesino atrapado en bucle temporal debe eliminar 8 objetivos en isla Blackreef",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Arkane Studios",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1252330/header.jpg",
  },
  {
    id: "37",
    nombre: "It Takes Two",
    genero: "Cooperativo/Aventura",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Aventura cooperativa obligatoria de pareja transformada en muñecos",
    precio: "39.99",
    tematica: "Fantasía",
    desarrollador: "Hazelight Studios",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/header.jpg",
  },
  {
    id: "38",
    nombre: "A Way Out",
    genero: "Cooperativo/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Cooperativo narrativo de escape de prisión split-screen obligatorio",
    precio: "29.99",
    tematica: "Contemporáneo",
    desarrollador: "Hazelight Studios",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/391830/header.jpg",
  },
  {
    id: "39",
    nombre: "Monster Hunter: World",
    genero: "Acción/RPG",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Caza cooperativa de monstruos gigantes en ecosistemas vivos del Nuevo Mundo",
    precio: "29.99",
    tematica: "Fantasía",
    desarrollador: "Capcom",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg",
  },
  {
    id: "40",
    nombre: "Monster Hunter Rise",
    genero: "Acción/RPG",
    plataforma: "PC/Switch",
    descripcion:
      "Caza de monstruos con Wirebugs permitiendo movilidad vertical en Kamura",
    precio: "39.99",
    tematica: "Fantasía Japonesa",
    desarrollador: "Capcom",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1446250/header.jpg",
  },
  {
    id: "41",
    nombre: "Final Fantasy VII Remake",
    genero: "JRPG",
    plataforma: "PC/PS5",
    descripcion:
      "Remake expandido de FF7 con combate en tiempo real en ciudad Midgar",
    precio: "59.99",
    tematica: "Fantasía/Steampunk",
    desarrollador: "Square Enix",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1462360/header.jpg",
  },
  {
    id: "42",
    nombre: "Final Fantasy XVI",
    genero: "JRPG/Acción",
    plataforma: "PS5",
    descripcion:
      "RPG de acción medieval con Eikons (invocaciones) en guerra de naciones",
    precio: "69.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Square Enix",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/10/2/3764027_front.jpg",
  },
  {
    id: "43",
    nombre: "Dragon Age: Inquisition",
    genero: "RPG",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "RPG táctico liderando Inquisición contra brecha demoníaca en Thedas",
    precio: "39.99",
    tematica: "Fantasía Medieval",
    desarrollador: "BioWare",
    año: "2014",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1222690/header.jpg",
  },
  {
    id: "44",
    nombre: "Mass Effect Legendary Edition",
    genero: "RPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Trilogía remasterizada de space opera con decisiones que persisten",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "BioWare",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1238040/header.jpg",
  },
  {
    id: "45",
    nombre: "Assassin's Creed Valhalla",
    genero: "Acción/RPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Vikingo Eivor conquista Inglaterra sajona en edad oscura con sigilo y saqueo",
    precio: "59.99",
    tematica: "Histórico/Vikingo",
    desarrollador: "Ubisoft",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2208920/header.jpg",
  },
  {
    id: "46",
    nombre: "Assassin's Creed Origins",
    genero: "Acción/RPG",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Origen de la Hermandad en Egipto ptolemaico con Bayek como Medjay",
    precio: "39.99",
    tematica: "Histórico/Egipto",
    desarrollador: "Ubisoft",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/582160/header.jpg",
  },
  {
    id: "47",
    nombre: "Far Cry 6",
    genero: "FPS/Acción",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Revolución contra dictador Anton Castillo en isla tropical Yara",
    precio: "59.99",
    tematica: "Contemporáneo",
    desarrollador: "Ubisoft",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1352070/header.jpg",
  },
  {
    id: "48",
    nombre: "Watch Dogs: Legion",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Recluta cualquier NPC para DedSec liberando Londres distópico vigilado",
    precio: "49.99",
    tematica: "Cyberpunk",
    desarrollador: "Ubisoft",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1255980/header.jpg",
  },
  {
    id: "49",
    nombre: "Immortals Fenyx Rising",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Aventura mitológica griega con puzzles físicos y combate estilo Zelda",
    precio: "49.99",
    tematica: "Mitología Griega",
    desarrollador: "Ubisoft",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/992210/header.jpg",
  },
  {
    id: "50",
    nombre: "Gears 5",
    genero: "TPS",
    plataforma: "PC/Xbox",
    descripcion:
      "Shooter cover-based contra Swarm con Kait descubriendo su conexión Locust",
    precio: "39.99",
    tematica: "Ciencia Ficción",
    desarrollador: "The Coalition",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1097840/header.jpg",
  },
  {
    id: "51",
    nombre: "Halo Infinite",
    genero: "FPS",
    plataforma: "PC/Xbox",
    descripcion:
      "Master Chief en anillo Zeta con gancho y mundo semi-abierto contra Desterrados",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "343 Industries",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg",
  },
  {
    id: "52",
    nombre: "Forza Horizon 5",
    genero: "Carreras",
    plataforma: "PC/Xbox",
    descripcion:
      "Festival de carreras arcade en México abierto con cientos de coches",
    precio: "59.99",
    tematica: "Contemporáneo",
    desarrollador: "Playground Games",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
  },
  {
    id: "53",
    nombre: "Gran Turismo 7",
    genero: "Carreras",
    plataforma: "PS5",
    descripcion:
      "Simulador realista de carreras con GT Café y colección masiva de vehículos",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "Polyphony Digital",
    año: "2022",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/10/0/3875578_front.jpg",
  },
  {
    id: "54",
    nombre: "F1 2023",
    genero: "Carreras",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Simulador oficial de Fórmula 1 con todas las pistas y pilotos de temporada",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "Codemasters",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2109040/header.jpg",
  },
  {
    id: "55",
    nombre: "FIFA 24",
    genero: "Deportes",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Simulador de fútbol EA Sports FC con Ultimate Team y Career Mode",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "EA Sports",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2255420/header.jpg",
  },
  {
    id: "56",
    nombre: "NBA 2K24",
    genero: "Deportes",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Simulador de baloncesto con MyCareer y jugadores NBA actualizados",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "2K Sports",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1967206/header.jpg",
  },
  {
    id: "57",
    nombre: "MLB The Show 23",
    genero: "Deportes",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Béisbol simulación con Diamond Dynasty y Road to the Show",
    precio: "59.99",
    tematica: "Contemporáneo",
    desarrollador: "Sony San Diego",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1924920/header.jpg",
  },
  {
    id: "58",
    nombre: "Madden NFL 24",
    genero: "Deportes",
    plataforma: "PC/PS5/Xbox",
    descripcion: "Fútbol americano con Franchise Mode y equipos NFL completos",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "EA Sports",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1865080/header.jpg",
  },
  {
    id: "59",
    nombre: "Rocket League",
    genero: "Deportes/Arcade",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Fútbol con coches propulsados por cohetes en partidas competitivas",
    precio: "Free",
    tematica: "Futurista",
    desarrollador: "Psyonix",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg",
  },
  {
    id: "60",
    nombre: "Fall Guys",
    genero: "Party/Battle Royale",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Battle royale de minijuegos coloridos para 60 jugadores",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "Mediatonic",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1193120/header.jpg",
  },
  {
    id: "61",
    nombre: "Among Us",
    genero: "Social Deduction",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Deducción social encontrando impostores saboteando nave espacial",
    precio: "5.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Innersloth",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg",
  },
  {
    id: "62",
    nombre: "Overcooked 2",
    genero: "Cooperativo/Puzzle",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Cocina cooperativa caótica completando pedidos en cocinas imposibles",
    precio: "24.99",
    tematica: "Fantasía",
    desarrollador: "Ghost Town Games",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/448510/header.jpg",
  },
  {
    id: "63",
    nombre: "Cuphead",
    genero: "Run and Gun",
    plataforma: "PC/Xbox/Switch/PS4",
    descripcion:
      "Run and gun con gráficos años 30 y jefes brutalmente difíciles",
    precio: "19.99",
    tematica: "Cartoon",
    desarrollador: "Studio MDHR",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg",
  },
  {
    id: "64",
    nombre: "Ori and the Blind Forest",
    genero: "Metroidvania",
    plataforma: "PC/Xbox/Switch",
    descripcion:
      "Metroidvania emocional con plataformas precisas en bosque bioluminiscente",
    precio: "19.99",
    tematica: "Fantasía",
    desarrollador: "Moon Studios",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/261570/header.jpg",
  },
  {
    id: "65",
    nombre: "Ori and the Will of the Wisps",
    genero: "Metroidvania",
    plataforma: "PC/Xbox/Switch",
    descripcion:
      "Secuela expandida de Ori con combate mejorado y mundo más grande",
    precio: "29.99",
    tematica: "Fantasía",
    desarrollador: "Moon Studios",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1097480/header.jpg",
  },
  {
    id: "66",
    nombre: "Minecraft",
    genero: "Sandbox",
    plataforma: "PC/PS5/Xbox/Switch/Mobile",
    descripcion:
      "Construcción y supervivencia en mundos procedurales de bloques infinitos",
    precio: "26.95",
    tematica: "Fantasía",
    desarrollador: "Mojang Studios",
    año: "2011",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/663403_front.jpg",
  },
  {
    id: "67",
    nombre: "Terraria",
    genero: "Sandbox",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Exploración 2D con construcción minería y combate contra jefes épicos",
    precio: "9.99",
    tematica: "Fantasía",
    desarrollador: "Re-Logic",
    año: "2011",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg",
  },
  {
    id: "68",
    nombre: "No Man's Sky",
    genero: "Exploración/Supervivencia",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Exploración espacial procedural con quintillones de planetas y bases",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Hello Games",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg",
  },
  {
    id: "69",
    nombre: "Subnautica",
    genero: "Supervivencia",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Supervivencia submarina en planeta alienígena 4546B con criaturas abisales",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Unknown Worlds",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/264710/header.jpg",
  },
  {
    id: "70",
    nombre: "The Forest",
    genero: "Supervivencia/Horror",
    plataforma: "PC/PS4",
    descripcion:
      "Supervivencia en isla con caníbales mutantes buscando hijo perdido",
    precio: "19.99",
    tematica: "Horror",
    desarrollador: "Endnight Games",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/242760/header.jpg",
  },
  {
    id: "71",
    nombre: "Valheim",
    genero: "Supervivencia",
    plataforma: "PC",
    descripcion:
      "Supervivencia vikinga cooperativa en purgatorio nórdico procedural",
    precio: "19.99",
    tematica: "Mitología Nórdica",
    desarrollador: "Iron Gate Studio",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg",
  },
  {
    id: "72",
    nombre: "Satisfactory",
    genero: "Construcción",
    plataforma: "PC",
    descripcion:
      "Factoría en primera persona en planeta alienígena con automatización masiva",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Coffee Stain Studios",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/526870/header.jpg",
  },
  {
    id: "73",
    nombre: "Factorio",
    genero: "Construcción",
    plataforma: "PC",
    descripcion:
      "Construcción de fábrica automatizada defendiendo de alienígenas nativos",
    precio: "30.00",
    tematica: "Ciencia Ficción",
    desarrollador: "Wube Software",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg",
  },
  {
    id: "74",
    nombre: "Cities: Skylines",
    genero: "Simulación",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Simulador de construcción de ciudades con zonificación y gestión de tráfico",
    precio: "29.99",
    tematica: "Contemporáneo",
    desarrollador: "Colossal Order",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/255710/header.jpg",
  },
  {
    id: "75",
    nombre: "Planet Zoo",
    genero: "Simulación",
    plataforma: "PC",
    descripcion:
      "Gestión detallada de zoológico con bienestar animal y construcción libre",
    precio: "44.99",
    tematica: "Contemporáneo",
    desarrollador: "Frontier Developments",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/703080/header.jpg",
  },
  {
    id: "76",
    nombre: "RimWorld",
    genero: "Simulación/Estrategia",
    plataforma: "PC/PS4/Xbox",
    descripcion: "Simulador de colonia sci-fi narrado por una IA cuentacuentos",
    precio: "34.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Ludeon Studios",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/header.jpg",
  },
  {
    id: "77",
    nombre: "Sid Meier's Civilization VI",
    genero: "Estrategia",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Estrategia por turnos 4X construyendo un imperio desde la antigüedad",
    precio: "59.99",
    tematica: "Histórico",
    desarrollador: "Firaxis Games",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg",
  },
  {
    id: "78",
    nombre: "Stellaris",
    genero: "Estrategia",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Estrategia gran escala 4X explorando galaxia y gestionando imperio espacial",
    precio: "39.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Paradox Development Studio",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/281990/header.jpg",
  },
  {
    id: "79",
    nombre: "Crusader Kings III",
    genero: "Estrategia/RPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Simulador de dinastía medieval con intrigas políticas y gestión de linaje",
    precio: "49.99",
    tematica: "Histórico Medieval",
    desarrollador: "Paradox Development Studio",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1158310/header.jpg",
  },
  {
    id: "80",
    nombre: "Total War: Warhammer III",
    genero: "Estrategia",
    plataforma: "PC",
    descripcion:
      "Batallas tácticas masivas en tiempo real y gestión de campaña en mundo Warhammer",
    precio: "59.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Creative Assembly",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1142710/header.jpg",
  },
  {
    id: "81",
    nombre: "Age of Empires IV",
    genero: "Estrategia",
    plataforma: "PC/Xbox",
    descripcion:
      "Estrategia en tiempo real clásica regresando a épocas históricas medievales",
    precio: "39.99",
    tematica: "Histórico Medieval",
    desarrollador: "Relic Entertainment",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1466860/header.jpg",
  },
  {
    id: "82",
    nombre: "Starcraft II",
    genero: "Estrategia",
    plataforma: "PC",
    descripcion:
      "RTS competitivo definitivo con tres facciones: Terran Zerg y Protoss",
    precio: "Free",
    tematica: "Ciencia Ficción",
    desarrollador: "Blizzard Entertainment",
    año: "2010",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/624944_front.jpg",
  },
  {
    id: "83",
    nombre: "XCOM 2",
    genero: "Estrategia",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Estrategia táctica por turnos liderando resistencia contra ocupación alienígena",
    precio: "49.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Firaxis Games",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/268500/header.jpg",
  },
  {
    id: "84",
    nombre: "Fire Emblem: Three Houses",
    genero: "Estrategia/RPG",
    plataforma: "Switch",
    descripcion:
      "RPG táctico por turnos como profesor de academia militar en Fódlan",
    precio: "59.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Intelligent Systems",
    año: "2019",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/685110_front.jpg",
  },
  {
    id: "85",
    nombre: "Triangle Strategy",
    genero: "Estrategia/RPG",
    plataforma: "PC/Switch",
    descripcion:
      "RPG táctico con estilo HD-2D y decisiones políticas que afectan la historia",
    precio: "59.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Square Enix",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1850510/header.jpg",
  },
  {
    id: "86",
    nombre: "Inscryption",
    genero: "Cartas/Roguelike",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Juego de cartas oscuro con elementos de escape room y misterio metaficcional",
    precio: "19.99",
    tematica: "Horror",
    desarrollador: "Daniel Mullins Games",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1092790/header.jpg",
  },
  {
    id: "87",
    nombre: "Slay the Spire",
    genero: "Cartas/Roguelike",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Roguelike de construcción de mazos ascendiendo una torre con reliquias",
    precio: "24.99",
    tematica: "Fantasía",
    desarrollador: "Mega Crit Games",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/646570/header.jpg",
  },
  {
    id: "88",
    nombre: "Marvel's Snap",
    genero: "Cartas",
    plataforma: "PC/Mobile",
    descripcion:
      "Juego de cartas rápido de Marvel con mecánicas de apuesta y localizaciones",
    precio: "Free",
    tematica: "Superhéroes",
    desarrollador: "Second Dinner",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1997040/header.jpg",
  },
  {
    id: "89",
    nombre: "Hearthstone",
    genero: "Cartas",
    plataforma: "PC/Mobile",
    descripcion:
      "Juego de cartas coleccionables competitivo en universo Warcraft",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "Blizzard Entertainment",
    año: "2014",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/705708_front.jpg",
  },
  {
    id: "90",
    nombre: "Gwent: The Witcher Card Game",
    genero: "Cartas",
    plataforma: "PC/Mobile",
    descripcion: "Juego de cartas táctico basado en minijuego de The Witcher 3",
    precio: "Free",
    tematica: "Fantasía Medieval",
    desarrollador: "CD Projekt Red",
    año: "2018",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/781075_front.jpg",
  },
  {
    id: "91",
    nombre: "Sea of Thieves",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Vida pirata cooperativa en mundo abierto buscando tesoros y combatiendo barcos",
    precio: "39.99",
    tematica: "Piratas",
    desarrollador: "Rare",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg",
  },
  {
    id: "92",
    nombre: "Destiny 2",
    genero: "FPS/MMO",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Looter shooter espacial defendiendo última ciudad de Tierra contra oscuridad",
    precio: "Free",
    tematica: "Ciencia Ficción",
    desarrollador: "Bungie",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg",
  },
  {
    id: "93",
    nombre: "Warframe",
    genero: "Acción/RPG",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Ninjas espaciales con armaduras bio-metálicas en misiones cooperativas",
    precio: "Free",
    tematica: "Ciencia Ficción",
    desarrollador: "Digital Extremes",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg",
  },
  {
    id: "94",
    nombre: "Genshin Impact",
    genero: "Acción/RPG",
    plataforma: "PC/PS5/Mobile",
    descripcion:
      "Mundo abierto masivo con sistema elemental y personajes coleccionables gacha",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "HoYoverse",
    año: "2020",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/815750_front.jpg",
  },
  {
    id: "95",
    nombre: "Honkai: Star Rail",
    genero: "RPG por turnos",
    plataforma: "PC/PS5/Mobile",
    descripcion:
      "Aventura espacial por turnos con personajes carismáticos y viaje galáctico",
    precio: "Free",
    tematica: "Ciencia Ficción/Fantasía",
    desarrollador: "HoYoverse",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/1032890_front.jpg",
  },
  {
    id: "96",
    nombre: "Final Fantasy XIV",
    genero: "MMORPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "MMORPG masivo con narrativa profunda y comunidad acogedora en Eorzea",
    precio: "19.99 + Sub",
    tematica: "Fantasía Medieval",
    desarrollador: "Square Enix",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/39210/header.jpg",
  },
  {
    id: "97",
    nombre: "World of Warcraft",
    genero: "MMORPG",
    plataforma: "PC",
    descripcion:
      "Referente histórico de MMORPG explorando Azeroth con expansión continua",
    precio: "12.99/mes",
    tematica: "Fantasía Medieval",
    desarrollador: "Blizzard Entertainment",
    año: "2004",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/559813_front.jpg",
  },
  {
    id: "98",
    nombre: "Guild Wars 2",
    genero: "MMORPG",
    plataforma: "PC",
    descripcion:
      "MMORPG centrado en eventos dinámicos y combate fluido sin cuotas mensuales",
    precio: "Free",
    tematica: "Fantasía Medieval",
    desarrollador: "ArenaNet",
    año: "2012",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/675549_front.jpg",
  },
  {
    id: "99",
    nombre: "The Elder Scrolls Online",
    genero: "MMORPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Explora todo Tamriel en este MMORPG con historia fully voiced",
    precio: "19.99",
    tematica: "Fantasía Medieval",
    desarrollador: "ZeniMax Online Studios",
    año: "2014",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/306130/header.jpg",
  },
  {
    id: "100",
    nombre: "Lost Ark",
    genero: "MMORPG/ARPG",
    plataforma: "PC",
    descripcion:
      "MMO de acción con perspectiva isométrica y combate espectacular",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "Smilegate RPG",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg",
  },
  {
    id: "101",
    nombre: "Baldur's Gate 2: Shadows of Amn",
    genero: "RPG",
    plataforma: "PC",
    descripcion:
      "Clásico absoluto del RPG isométrico basado en AD&D en Reinos Olvidados",
    precio: "19.99",
    tematica: "Fantasía Medieval",
    desarrollador: "BioWare",
    año: "2000",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/257350/header.jpg",
  },
  {
    id: "102",
    nombre: "Diablo IV",
    genero: "ARPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Regreso a la oscuridad de Santuario con mundo abierto y loot infinito",
    precio: "69.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Blizzard Entertainment",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2344520/header.jpg",
  },
  {
    id: "103",
    nombre: "Path of Exile",
    genero: "ARPG",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "ARPG complejo con árbol de habilidades masivo y economía profunda",
    precio: "Free",
    tematica: "Fantasía Oscura",
    desarrollador: "Grinding Gear Games",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg",
  },
  {
    id: "104",
    nombre: "Hades II",
    genero: "Roguelike",
    plataforma: "PC",
    descripcion:
      "Secuela del aclamado roguelike controlando a Melinoë contra Cronos",
    precio: "29.99",
    tematica: "Mitología Griega",
    desarrollador: "Supergiant Games",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg",
  },
  {
    id: "105",
    nombre: "Dead Space Remake",
    genero: "Survival Horror",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Remake fiel y aterrador del clásico de terror espacial en la Ishimura",
    precio: "59.99",
    tematica: "Ciencia Ficción/Horror",
    desarrollador: "Motive Studio",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg",
  },
  {
    id: "106",
    nombre: "Alan Wake 2",
    genero: "Survival Horror",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Misterio psicológico entrelazando historias de Alan Wake y Saga Anderson",
    precio: "59.99",
    tematica: "Horror/Sobrenatural",
    desarrollador: "Remedy Entertainment",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "107",
    nombre: "Silent Hill 2 Remake",
    genero: "Survival Horror",
    plataforma: "PC/PS5",
    descripcion:
      "Remake emocional y visualmente impactante del mejor horror psicológico",
    precio: "69.99",
    tematica: "Horror Psicológico",
    desarrollador: "Bloober Team",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2124490/header.jpg",
  },
  {
    id: "108",
    nombre: "Phasmophobia",
    genero: "Horror",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Investigación cooperativa de fantasmas usando herramientas de detección",
    precio: "13.99",
    tematica: "Sobrenatural",
    desarrollador: "Kinetic Games",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg",
  },
  {
    id: "109",
    nombre: "Amnesia: The Bunker",
    genero: "Horror/Survival",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Terror claustrofóbico en bunker de 1GM con criatura acechante dinámica",
    precio: "24.99",
    tematica: "Histórico/Horror",
    desarrollador: "Frictional Games",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1944430/header.jpg",
  },
  {
    id: "110",
    nombre: "Outer Wilds: Echoes of the Eye",
    genero: "Aventura/Puzzle",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Expansión masiva que añade nuevo mundo y misterio al universo Outer Wilds",
    precio: "14.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Mobius Digital",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1626360/header.jpg",
  },
  {
    id: "111",
    nombre: "Starfield",
    genero: "RPG/Acción",
    plataforma: "PC/Xbox",
    descripcion:
      "RPG espacial de Bethesda explorando 1000 planetas y construyendo naves",
    precio: "69.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Bethesda Game Studios",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg",
  },
  {
    id: "112",
    nombre: "Skyrim",
    genero: "RPG",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Épica de fantasía de mundo abierto con libertad total y miles de mods",
    precio: "39.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Bethesda Game Studios",
    año: "2011",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg",
  },
  {
    id: "113",
    nombre: "Fallout 4",
    genero: "RPG/Acción",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Supervivencia post-nuclear en Boston construyendo asentamientos",
    precio: "19.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Bethesda Game Studios",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/377160/header.jpg",
  },
  {
    id: "114",
    nombre: "Fallout: New Vegas",
    genero: "RPG/Acción",
    plataforma: "PC/Xbox",
    descripcion:
      "RPG profundo en Mojave con facciones complejas y narrativa ramificada",
    precio: "9.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Obsidian Entertainment",
    año: "2010",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/22380/header.jpg",
  },
  {
    id: "115",
    nombre: "The Outer Worlds",
    genero: "RPG/Acción",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "RPG satírico espacial en colonias corporatizadas con humor y decisiones",
    precio: "29.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Obsidian Entertainment",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/header.jpg",
  },
  {
    id: "116",
    nombre: "Armored Core VI: Fires of Rubicon",
    genero: "Acción/Mechas",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Combate intenso de mechas personalizables con jugabilidad de FromSoftware",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "FromSoftware",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1888160/header.jpg",
  },
  {
    id: "117",
    nombre: "Street Fighter 6",
    genero: "Lucha",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Reinvención de la saga de lucha con World Tour y controles modernos",
    precio: "59.99",
    tematica: "Contemporáneo",
    desarrollador: "Capcom",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1364780/header.jpg",
  },
  {
    id: "118",
    nombre: "Tekken 8",
    genero: "Lucha",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Evolución visual y técnica del combate 3D con sistema Heat agresivo",
    precio: "69.99",
    tematica: "Contemporáneo",
    desarrollador: "Bandai Namco",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1778820/header.jpg",
  },
  {
    id: "119",
    nombre: "Mortal Kombat 1",
    genero: "Lucha",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Reinicio del universo Mortal Kombat con sistema de Kameos",
    precio: "69.99",
    tematica: "Fantasía/Gore",
    desarrollador: "NetherRealm Studios",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg",
  },
  {
    id: "120",
    nombre: "Guilty Gear Strive",
    genero: "Lucha",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Lucha anime con visuales espectaculares y netcode de alta calidad",
    precio: "39.99",
    tematica: "Anime",
    desarrollador: "Arc System Works",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1384300/header.jpg",
  },
  {
    id: "121",
    nombre: "Dragon Ball FighterZ",
    genero: "Lucha",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Lucha 3v3 frenética recreando fielmente el estilo de Akira Toriyama",
    precio: "59.99",
    tematica: "Anime/Dragon Ball",
    desarrollador: "Arc System Works",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/678950/header.jpg",
  },
  {
    id: "122",
    nombre: "Devil May Cry 5",
    genero: "Acción/Hack & Slash",
    plataforma: "PC/PS5/Xbox",
    descripcion: "Hack and slash con estilo exagerado y tres personajes únicos",
    precio: "29.99",
    tematica: "Fantasía Urbana",
    desarrollador: "Capcom",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/601150/header.jpg",
  },
  {
    id: "123",
    nombre: "Bayonetta 3",
    genero: "Acción/Hack & Slash",
    plataforma: "Switch",
    descripcion:
      "Clímax de acción con la bruja Umbra invocando demonios gigantes",
    precio: "59.99",
    tematica: "Fantasía Urbana",
    desarrollador: "PlatinumGames",
    año: "2022",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/6/761106_front.jpg",
  },
  {
    id: "124",
    nombre: "NieR: Automata",
    genero: "Acción/RPG",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Obra maestra filosófica sobre androides en mundo post-apocalíptico",
    precio: "39.99",
    tematica: "Ciencia Ficción",
    desarrollador: "PlatinumGames",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/524220/header.jpg",
  },
  {
    id: "125",
    nombre: "Batman: Arkham Knight",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Conclusión de la saga Arkham con Batmóvil explorable en Gotham",
    precio: "19.99",
    tematica: "Superhéroes/DC",
    desarrollador: "Rocksteady Studios",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/208650/header.jpg",
  },
  {
    id: "126",
    nombre: "Insomniac's Spider-Man 2",
    genero: "Acción/Aventura",
    plataforma: "PS5",
    descripcion:
      "Aventura épica controlando a Peter y Miles contra Venom y Kraven",
    precio: "69.99",
    tematica: "Superhéroes/Marvel",
    desarrollador: "Insomniac Games",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "127",
    nombre: "Uncharted 4: A Thief's End",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Final del viaje de Nathan Drake buscando tesoro pirata de Libertalia",
    precio: "39.99",
    tematica: "Aventura/Tesoro",
    desarrollador: "Naughty Dog",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1659420/header.jpg",
  },
  {
    id: "128",
    nombre: "Tomb Raider (2013)",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Reinicio de Lara Croft sobreviviendo en isla misteriosa de Yamatai",
    precio: "14.99",
    tematica: "Aventura/Supervivencia",
    desarrollador: "Crystal Dynamics",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/203160/header.jpg",
  },
  {
    id: "129",
    nombre: "Lies of P",
    genero: "Souls-like",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Souls-like oscuro basado en Pinocho en ciudad Belle Époque Krat",
    precio: "59.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Neowiz Games",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1446780/header.jpg",
  },
  {
    id: "130",
    nombre: "Remnant 2",
    genero: "Soulslike/TPS",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Shooter souls-like cooperativo con mundos generados proceduralmente",
    precio: "49.99",
    tematica: "Ciencia Ficción/Fantasía",
    desarrollador: "Gunfire Games",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1282100/header.jpg",
  },
  {
    id: "131",
    nombre: "Black Myth: Wukong",
    genero: "Acción/RPG",
    plataforma: "PC/PS5",
    descripcion:
      "Acción épica inspirada en Viaje al Oeste con gráficos next-gen",
    precio: "59.99",
    tematica: "Mitología China",
    desarrollador: "Game Science",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
  },
  {
    id: "132",
    nombre: "Kingdom Come: Deliverance",
    genero: "RPG",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion: "RPG medieval realista sin elementos de fantasía en Bohemia",
    precio: "29.99",
    tematica: "Histórico Medieval",
    desarrollador: "Warhorse Studios",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/379430/header.jpg",
  },
  {
    id: "133",
    nombre: "Mount & Blade II: Bannerlord",
    genero: "RPG/Estrategia",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Simulador de guerra medieval liderando ejércitos y forjando reinos",
    precio: "49.99",
    tematica: "Histórico Medieval",
    desarrollador: "TaleWorlds Entertainment",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/261550/header.jpg",
  },
  {
    id: "134",
    nombre: "Chivalry 2",
    genero: "Acción/Multijugador",
    plataforma: "PC/PS5/Xbox",
    descripcion: "Batallas medievales masivas multijugador con combate técnico",
    precio: "39.99",
    tematica: "Histórico Medieval",
    desarrollador: "Torn Banner Studios",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1824220/header.jpg",
  },
  {
    id: "135",
    nombre: "Hellblade: Senua's Sacrifice",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Viaje psicológico intenso de guerrera celta al inframundo nórdico",
    precio: "29.99",
    tematica: "Mitología Nórdica",
    desarrollador: "Ninja Theory",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/414340/header.jpg",
  },
  {
    id: "136",
    nombre: "The Legend of Zelda: Link's Awakening",
    genero: "Aventura",
    plataforma: "Switch",
    descripcion: "Encantador remake del clásico de GameBoy en Isla Koholint",
    precio: "59.99",
    tematica: "Fantasía",
    desarrollador: "Nintendo",
    año: "2019",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/5/5/5/723555_front.jpg",
  },
  {
    id: "137",
    nombre: "Metroid Dread",
    genero: "Metroidvania",
    plataforma: "Switch",
    descripcion:
      "Regreso triunfal de Samus en 2D siendo perseguida por robots E.M.M.I.",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "MercurySteam",
    año: "2021",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "138",
    nombre: "Metroid Prime Remastered",
    genero: "Aventura/FPS",
    plataforma: "Switch",
    descripcion:
      "Remasterización perfecta del clásico de GameCube en primera persona",
    precio: "39.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Retro Studios",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "139",
    nombre: "Super Smash Bros. Ultimate",
    genero: "Lucha",
    plataforma: "Switch",
    descripcion:
      "Crossover definitivo con todos los luchadores de la historia de Smash",
    precio: "59.99",
    tematica: "Nintendo/Crossover",
    desarrollador: "Nintendo",
    año: "2018",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "140",
    nombre: "Mario Kart 8 Deluxe",
    genero: "Carreras",
    plataforma: "Switch",
    descripcion:
      "El juego de karts definitivo con 48 pistas y multijugador masivo",
    precio: "59.99",
    tematica: "Fantasía/Mario",
    desarrollador: "Nintendo",
    año: "2017",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "141",
    nombre: "Splatoon 3",
    genero: "Shooter/Multijugador",
    plataforma: "Switch",
    descripcion: "Batallas de tinta por equipos con Inklings y Octolings",
    precio: "59.99",
    tematica: "Fantasía",
    desarrollador: "Nintendo",
    año: "2022",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "142",
    nombre: "Animal Crossing: New Horizons",
    genero: "Simulación",
    plataforma: "Switch",
    descripcion:
      "Crea tu propio paraíso en una isla desierta con vecinos animales",
    precio: "59.99",
    tematica: "Relajante",
    desarrollador: "Nintendo",
    año: "2020",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "143",
    nombre: "Xenoblade Chronicles 3",
    genero: "JRPG",
    plataforma: "Switch",
    descripcion:
      "RPG épico sobre la vida y la guerra con mundo masivo explorable",
    precio: "59.99",
    tematica: "Ciencia Ficción/Fantasía",
    desarrollador: "Monolith Soft",
    año: "2022",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "144",
    nombre: "Fire Emblem Engage",
    genero: "Estrategia/RPG",
    plataforma: "Switch",
    descripcion:
      "Combate táctico refinado invocando héroes clásicos de la saga",
    precio: "59.99",
    tematica: "Fantasía Medieval",
    desarrollador: "Intelligent Systems",
    año: "2023",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "145",
    nombre: "Paper Mario: The Thousand-Year Door",
    genero: "RPG",
    plataforma: "Switch",
    descripcion:
      "Remake del querido RPG de Mario con estilo de papel y gran humor",
    precio: "59.99",
    tematica: "Fantasía",
    desarrollador: "Intelligent Systems",
    año: "2024",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/1/0/2/385102_front.jpg",
  },
  {
    id: "146",
    nombre: "Outer Wilds",
    genero: "Aventura/Exploración",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Misterio espacial en bucle temporal con exploración no lineal",
    precio: "24.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Mobius Digital",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/753640/header.jpg",
  },
  {
    id: "147",
    nombre: "Tunic",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Pequeño zorro explora mundo lleno de secretos con manual retro",
    precio: "29.99",
    tematica: "Fantasía",
    desarrollador: "Andrew Shouldice",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/553420/header.jpg",
  },
  {
    id: "148",
    nombre: "Dave the Diver",
    genero: "Aventura/Simulación",
    plataforma: "PC/PS5/Switch",
    descripcion:
      "Buceo de día para pescar y gestión de restaurante sushi de noche",
    precio: "19.99",
    tematica: "Casual",
    desarrollador: "MINTROCKET",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1868140/header.jpg",
  },
  {
    id: "149",
    nombre: "Sea of Stars",
    genero: "JRPG",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "RPG por turnos inspirado en clásicos con arte pixelart precioso",
    precio: "34.99",
    tematica: "Fantasía",
    desarrollador: "Sabotage Studio",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1244090/header.jpg",
  },
  {
    id: "150",
    nombre: "Dredge",
    genero: "Aventura/Pesca/Horror",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Pesca en archipiélago con misterios lovecraftianos bajo el agua",
    precio: "24.99",
    tematica: "Horror Cósmico",
    desarrollador: "Black Salt Games",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1560520/header.jpg",
  },
  {
    id: "151",
    nombre: "Balatro",
    genero: "Roguelike/Cartas",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Roguelike de póker adictivo usando jokers y cartas mágicas",
    precio: "14.99",
    tematica: "Casino",
    desarrollador: "LocalThunk",
    año: "2024",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2379780/header.jpg",
  },
  {
    id: "152",
    nombre: "Vampire Survivors",
    genero: "Acción/Roguelike",
    plataforma: "PC/Xbox/Switch/Mobile",
    descripcion: "Supervivencia contra hordas masivas con ataques automáticos",
    precio: "4.99",
    tematica: "Horror Gótico",
    desarrollador: "poncle",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/header.jpg",
  },
  {
    id: "153",
    nombre: "Cult of the Lamb",
    genero: "Roguelike/Simulación",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Gestiona tu propia secta y combate en mazmorras como cordero",
    precio: "24.99",
    tematica: "Fantasía Oscura",
    desarrollador: "Massive Monster",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1313140/header.jpg",
  },
  {
    id: "154",
    nombre: "A Short Hike",
    genero: "Exploración",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Pequeña aventura relajante escalando parque natural Hawk Peak",
    precio: "7.99",
    tematica: "Relajante",
    desarrollador: "Adamgryu",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1055540/header.jpg",
  },
  {
    id: "155",
    nombre: "Untitled Goose Game",
    genero: "Puzzle/Stealth",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Eres un ganso travieso que debe molestar a los habitantes de un pueblo",
    precio: "19.99",
    tematica: "Humor",
    desarrollador: "House House",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1101910/header.jpg",
  },
  {
    id: "156",
    nombre: "Katana ZERO",
    genero: "Acción/Plataformas",
    plataforma: "PC/Xbox/Switch",
    descripcion: "Acción rápida 2D con manipulación del tiempo y estética neón",
    precio: "14.99",
    tematica: "Cyberpunk",
    desarrollador: "Askiisoft",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/460950/header.jpg",
  },
  {
    id: "157",
    nombre: "Neon White",
    genero: "FPS/Puzzle",
    plataforma: "PC/PS5/Switch",
    descripcion:
      "Shooter de velocidad usando cartas para parkour y eliminar demonios",
    precio: "24.99",
    tematica: "Anime",
    desarrollador: "Angel Matrix",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1533420/header.jpg",
  },
  {
    id: "158",
    nombre: "Sifu",
    genero: "Acción/Beat 'em up",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Combate Kung-Fu técnico donde envejeces cada vez que mueres",
    precio: "39.99",
    tematica: "Artes Marciales",
    desarrollador: "Sloclap",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2138710/header.jpg",
  },
  {
    id: "159",
    nombre: "Ghostrunner 2",
    genero: "Acción/Cyberpunk",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Acción intensa en primera persona con parkour y combate letal",
    precio: "39.99",
    tematica: "Cyberpunk",
    desarrollador: "One More Level",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2144740/header.jpg",
  },
  {
    id: "160",
    nombre: "Hi-Fi RUSH",
    genero: "Acción/Ritmo",
    plataforma: "PC/PS5/Xbox",
    descripcion: "Hack and slash donde todo ocurre al ritmo de la música",
    precio: "29.99",
    tematica: "Cartoon",
    desarrollador: "Tango Gameworks",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1817230/header.jpg",
  },
  {
    id: "161",
    nombre: "Portal 2",
    genero: "Puzzle",
    plataforma: "PC/PS3/Xbox 360/Switch",
    descripcion:
      "Obra maestra de puzzles usando portales con narrativa brillante",
    precio: "9.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Valve",
    año: "2011",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg",
  },
  {
    id: "162",
    nombre: "Half-Life: Alyx",
    genero: "FPS/VR",
    plataforma: "PC VR",
    descripcion:
      "La mejor experiencia VR hasta la fecha en el universo Half-Life",
    precio: "59.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Valve",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/546560/header.jpg",
  },
  {
    id: "163",
    nombre: "Left 4 Dead 2",
    genero: "FPS/Cooperativo",
    plataforma: "PC/Xbox 360",
    descripcion: "Shooter cooperativo de zombies frenético y rejugable",
    precio: "9.99",
    tematica: "Zombies",
    desarrollador: "Valve",
    año: "2009",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/550/header.jpg",
  },
  {
    id: "164",
    nombre: "Team Fortress 2",
    genero: "FPS/Multijugador",
    plataforma: "PC",
    descripcion:
      "Shooter basado en clases carismáticas con economía de sombreros",
    precio: "Free",
    tematica: "Cartoon",
    desarrollador: "Valve",
    año: "2007",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg",
  },
  {
    id: "165",
    nombre: "Dota 2",
    genero: "MOBA",
    plataforma: "PC",
    descripcion:
      "MOBA complejo y competitivo con profundidad estratégica infinita",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "Valve",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
  },
  {
    id: "166",
    nombre: "Counter-Strike: Global Offensive",
    genero: "FPS",
    plataforma: "PC",
    descripcion: "Shooter táctico competitivo referente en los esports",
    precio: "Free",
    tematica: "Contemporáneo",
    desarrollador: "Valve",
    año: "2012",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
  },
  {
    id: "167",
    nombre: "Life is Strange",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS4/Xbox/Mobile",
    descripcion:
      "Historia emocional de Max Caulfield pudiendo rebobinar el tiempo",
    precio: "19.99",
    tematica: "Drama",
    desarrollador: "Dontnod Entertainment",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/319630/header.jpg",
  },
  {
    id: "168",
    nombre: "What Remains of Edith Finch",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Exploración de casa familiar descubriendo historias de muertes trágicas",
    precio: "19.99",
    tematica: "Misterio",
    desarrollador: "Giant Sparrow",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/501300/header.jpg",
  },
  {
    id: "169",
    nombre: "Firewatch",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Vigilante forestal en Wyoming con relación vía radio misteriosa",
    precio: "19.99",
    tematica: "Misterio/Naturaleza",
    desarrollador: "Campo Santo",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/383870/header.jpg",
  },
  {
    id: "170",
    nombre: "The Stanley Parable: Ultra Deluxe",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Meta-narrativa surrealista sobre libertad de elección en oficina",
    precio: "24.99",
    tematica: "Sátira/Humor",
    desarrollador: "Crows Crows Crows",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1703340/header.jpg",
  },
  {
    id: "171",
    nombre: "Heavy Rain",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS4",
    descripcion:
      "Thriller psicológico sobre asesino del Origami con múltiples finales",
    precio: "19.99",
    tematica: "Crimen/Thriller",
    desarrollador: "Quantic Dream",
    año: "2010",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/960910/header.jpg",
  },
  {
    id: "172",
    nombre: "Detroit: Become Human",
    genero: "Aventura Narrativa",
    plataforma: "PC/PS4",
    descripcion:
      "Androides buscan libertad en futuro cercano con decisiones críticas",
    precio: "39.99",
    tematica: "Ciencia Ficción",
    desarrollador: "Quantic Dream",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1150640/header.jpg",
  },
  {
    id: "173",
    nombre: "Journey",
    genero: "Aventura/Exploración",
    plataforma: "PC/PS4",
    descripcion:
      "Viaje visual y musical hacia una montaña en desierto infinito",
    precio: "14.99",
    tematica: "Poético",
    desarrollador: "thatgamecompany",
    año: "2012",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/638230/header.jpg",
  },
  {
    id: "174",
    nombre: "Inside",
    genero: "Puzzle/Plataformas",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion: "Atmosférico y oscuro viaje de un niño en distopía industrial",
    precio: "19.99",
    tematica: "Horror/Distopía",
    desarrollador: "Playdead",
    año: "2016",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/304430/header.jpg",
  },
  {
    id: "175",
    nombre: "Limbo",
    genero: "Puzzle/Plataformas",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion: "Clásico indie en blanco y negro lleno de trampas mortales",
    precio: "9.99",
    tematica: "Horror",
    desarrollador: "Playdead",
    año: "2010",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/48000/header.jpg",
  },
  {
    id: "176",
    nombre: "Little Nightmares II",
    genero: "Horror/Puzzle",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Aventura de suspense controlando a Mono en mundo distorsionado",
    precio: "29.99",
    tematica: "Horror",
    desarrollador: "Tarsier Studios",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/860510/header.jpg",
  },
  {
    id: "177",
    nombre: "Super Meat Boy",
    genero: "Plataformas",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion: "Plataformas hardcore de precisión con trozo de carne animado",
    precio: "14.99",
    tematica: "Retro/Humor",
    desarrollador: "Team Meat",
    año: "2010",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/40800/header.jpg",
  },
  {
    id: "178",
    nombre: "Spelunky 2",
    genero: "Roguelike/Plataformas",
    plataforma: "PC/PS4/Xbox/Switch",
    descripcion:
      "Exploración de cuevas traicioneras con muertes constantes y sorpresas",
    precio: "19.99",
    tematica: "Aventura",
    desarrollador: "Mossmouth",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/418100/header.jpg",
  },
  {
    id: "179",
    nombre: "Papers, Please",
    genero: "Simulación/Puzzle",
    plataforma: "PC/Mobile",
    descripcion:
      "Inspector de fronteras en estado totalitario tomando decisiones morales",
    precio: "9.99",
    tematica: "Distopía/Político",
    desarrollador: "Lucas Pope",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/239030/header.jpg",
  },
  {
    id: "180",
    nombre: "Frostpunk",
    genero: "Estrategia/Supervivencia",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Gestiona la última ciudad de la tierra en invierno post-apocalíptico",
    precio: "29.99",
    tematica: "Steampunk/Post-apocalíptico",
    desarrollador: "11 bit studios",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/384570/header.jpg",
  },
  {
    id: "181",
    nombre: "This War of Mine",
    genero: "Supervivencia/Estrategia",
    plataforma: "PC/PS4/Xbox/Switch/Mobile",
    descripcion:
      "Sobrevive a una guerra desde la perspectiva de civiles asediados",
    precio: "19.99",
    tematica: "Guerra/Realista",
    desarrollador: "11 bit studios",
    año: "2014",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/282070/header.jpg",
  },
  {
    id: "182",
    nombre: "KOTOR - Star Wars: Knights of the Old Republic",
    genero: "RPG",
    plataforma: "PC/Xbox/Switch/Mobile",
    descripcion: "El mejor RPG de Star Wars con giro argumental legendario",
    precio: "9.99",
    tematica: "Ciencia Ficción/Star Wars",
    desarrollador: "BioWare",
    año: "2003",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/32370/header.jpg",
  },
  {
    id: "183",
    nombre: "Mass Effect 2",
    genero: "RPG/Acción",
    plataforma: "PC/PS3/Xbox 360",
    descripcion: "Misión suicida reuniendo al mejor equipo de la galaxia",
    precio: "19.99",
    tematica: "Ciencia Ficción",
    desarrollador: "BioWare",
    año: "2010",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/24980/header.jpg",
  },
  {
    id: "184",
    nombre: "Dragon Age: Origins",
    genero: "RPG",
    plataforma: "PC/PS3/Xbox 360",
    descripcion:
      "Sucesor espiritual de Baldur's Gate en mundo de fantasía oscura",
    precio: "19.99",
    tematica: "Fantasía Medieval",
    desarrollador: "BioWare",
    año: "2009",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/17450/header.jpg",
  },
  {
    id: "185",
    nombre: "Yakuza: Like a Dragon",
    genero: "JRPG",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Reinicio de Yakuza con combate por turnos y nuevo protagonista Ichiban",
    precio: "59.99",
    tematica: "Crimen/Humor",
    desarrollador: "Ryu Ga Gotoku Studio",
    año: "2020",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1235140/header.jpg",
  },
  {
    id: "186",
    nombre: "Judgment",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5/Xbox",
    descripcion:
      "Investigación detectivesca en Kamurocho como el abogado Takayuki Yagami",
    precio: "39.99",
    tematica: "Crimen/Misterio",
    desarrollador: "Ryu Ga Gotoku Studio",
    año: "2018",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2058180/header.jpg",
  },
  {
    id: "187",
    nombre: "Sleeping Dogs",
    genero: "Acción/Aventura",
    plataforma: "PC/PS4/Xbox",
    descripcion:
      "Policía encubierto en las tríadas de Hong Kong con combate brutal",
    precio: "19.99",
    tematica: "Crimen/Artes Marciales",
    desarrollador: "United Front Games",
    año: "2012",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/202170/header.jpg",
  },
  {
    id: "188",
    nombre: "Metal Gear Solid V: The Phantom Pain",
    genero: "Acción/Stealth",
    plataforma: "PC/PS4/Xbox",
    descripcion: "Sigilo táctico de mundo abierto definitivo con Big Boss",
    precio: "19.99",
    tematica: "Espionaje",
    desarrollador: "Kojima Productions",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/287700/header.jpg",
  },
  {
    id: "189",
    nombre: "Death Stranding Director's Cut",
    genero: "Acción/Aventura",
    plataforma: "PC/PS5",
    descripcion:
      "Versión definitiva del viaje de Sam Porter con nuevo contenido",
    precio: "49.99",
    tematica: "Post-apocalíptico",
    desarrollador: "Kojima Productions",
    año: "2021",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1850570/header.jpg",
  },
  {
    id: "190",
    nombre: "Kingdom Hearts III",
    genero: "Action RPG",
    plataforma: "PC/PS4/Xbox",
    descripcion: "Cierre de la saga de Sora visitando mundos de Disney y Pixar",
    precio: "59.99",
    tematica: "Fantasía/Disney",
    desarrollador: "Square Enix",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1408370/header.jpg",
  },
  {
    id: "191",
    nombre: "Fortnite",
    genero: "Battle Royale",
    plataforma: "PC/PS5/Xbox/Switch/Mobile",
    descripcion:
      "Battle Royale masivo con construcción eventos en vivo y colaboraciones",
    precio: "Free",
    tematica: "Crossover",
    desarrollador: "Epic Games",
    año: "2017",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/752101_front.jpg",
  },
  {
    id: "192",
    nombre: "Apex Legends",
    genero: "Battle Royale/FPS",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Hero shooter battle royale con movimiento fluido y leyendas únicas",
    precio: "Free",
    tematica: "Ciencia Ficción",
    desarrollador: "Respawn Entertainment",
    año: "2019",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg",
  },
  {
    id: "193",
    nombre: "PUBG: Battlegrounds",
    genero: "Battle Royale",
    plataforma: "PC/PS5/Xbox",
    descripcion: "BR original realista con múltiples mapas y gunplay táctico",
    precio: "Free",
    tematica: "Contemporáneo",
    desarrollador: "PUBG Corporation",
    año: "2017",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg",
  },
  {
    id: "194",
    nombre: "Valorant",
    genero: "FPS",
    plataforma: "PC",
    descripcion:
      "Tactical shooter 5v5 con agentes habilidades únicas estilo CS",
    precio: "Free",
    tematica: "Contemporáneo",
    desarrollador: "Riot Games",
    año: "2020",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/794296_front.jpg",
  },
  {
    id: "195",
    nombre: "Counter-Strike 2",
    genero: "FPS",
    plataforma: "PC",
    descripcion:
      "Tactical shooter competitivo remake en Source 2 con economía rondas",
    precio: "Free",
    tematica: "Contemporáneo",
    desarrollador: "Valve",
    año: "2023",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
  },
  {
    id: "196",
    nombre: "Overwatch 2",
    genero: "Hero Shooter",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion: "Hero shooter 5v5 con roles tanque daño y soporte",
    precio: "Free",
    tematica: "Futurista",
    desarrollador: "Blizzard Entertainment",
    año: "2022",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
  },
  {
    id: "197",
    nombre: "League of Legends",
    genero: "MOBA",
    plataforma: "PC",
    descripcion: "MOBA 5v5 con 160+ campeones en Summoner's Rift competitivo",
    precio: "Free",
    tematica: "Fantasía",
    desarrollador: "Riot Games",
    año: "2009",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/633363_front.jpg",
  },
  {
    id: "198",
    nombre: "Dota 2",
    genero: "MOBA",
    plataforma: "PC",
    descripcion:
      "MOBA complejo con héroes items y estrategia de equipo profunda",
    precio: "Free",
    tematica: "Fantasía Medieval",
    desarrollador: "Valve",
    año: "2013",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
  },
  {
    id: "199",
    nombre: "Rocket League",
    genero: "Deportes/Arcade",
    plataforma: "PC/PS5/Xbox/Switch",
    descripcion:
      "Fútbol con coches propulsados por cohetes en partidas competitivas",
    precio: "Free",
    tematica: "Futurista",
    desarrollador: "Psyonix",
    año: "2015",
    url_imagen:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg",
  },
  {
    id: "200",
    nombre: "Minecraft",
    genero: "Sandbox",
    plataforma: "PC/PS5/Xbox/Switch/Mobile",
    descripcion:
      "Construcción y supervivencia en mundos procedurales de bloques infinitos",
    precio: "26.95",
    tematica: "Fantasía",
    desarrollador: "Mojang Studios",
    año: "2011",
    url_imagen: "https://gamefaqs.gamespot.com/a/box/0/0/663403_front.jpg",
  },
];
